server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.137.35:3306/blogdb?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
picserver:
  rootpath: http://localhost:6060/

##DataSourceSettings#
##LocalDataSource: blogdb@192.168.137.35
##BEGIN#
#<data-source source="LOCAL" name="blogdb@192.168.137.35" uuid="7e7de9ff-f812-4dbb-aa01-56a102923db5"><database-info product="MySQL" version="5.5.12" jdbc-version="4.2" driver-name="MySQL Connector/J" driver-version="mysql-connector-java-8.0.25 (Revision: 08be9e9b4cba6aa115f9b27b215887af40b159e0)" dbms="MYSQL" exact-version="5.5.12" exact-driver-version="8.0"><extra-name-characters>#@</extra-name-characters><identifier-quote-string>`</identifier-quote-string></database-info><case-sensitivity plain-identifiers="lower" quoted-identifiers="lower"/><driver-ref>mysql.8</driver-ref><synchronize>true</synchronize><jdbc-driver>com.mysql.cj.jdbc.Driver</jdbc-driver><jdbc-url>jdbc:mysql://192.168.137.35:3306/blogdb</jdbc-url><secret-storage>master_key</secret-storage><user-name>root</user-name><schema-mapping><introspection-scope><node kind="schema"><name qname="@"/><name qname="blogdb"/></node></introspection-scope></schema-mapping><working-dir>$ProjectFileDir$</working-dir></data-source>
##END#


